services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile.apache
    ports:
      - "8090:80" # Apache écoute sur le port 8080
    volumes:
      - .:/usr/local/apache2/htdocs/
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: Dockerfile.phpfpm
    volumes:
      - .:/usr/local/apache2/htdocs/

