services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile.apache
    ports:
      - "8090:80" # Apache écoute sur le port 8080
    volumes:
      - .:/usr/local/apache2/htdocs/
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: Dockerfile.phpfpm
    volumes:
      - .:/usr/local/apache2/htdocs/
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
